# Generated by Django 4.2.14 on 2024-07-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="")),
            ],
        ),
    ]
